from kaspr.types.models.pycode import PyCode


class TopicNameSelector(PyCode): ...


class TopicPatternSelector(PyCode): ...


class TopicKeySelector(PyCode): ...


class TopicValueSelector(PyCode): ...


class TopicPartitionSelector(PyCode): ...


class TopicHeadersSelector(PyCode): ...


class TopicPredicate(PyCode): ...
